apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9tZWxiaW5wcG1hdGhld3A6bWVsYmluMTIzNDU2QGdsYXNzaWNzLnBrMDNpaWoubW9uZ29kYi5uZXQvYWRtaW5fc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA=="
  ADMIN_ACCESS_SECRET_TOKEN: "TUVwaUE4dTRBR0xYL1VFNnQrRlozVnExb2pzVFNUUHZuOE9rSTk1N2ZLY3lBTmhiYkY5bzZHTmFCMGdyVDVncWY3a3E5VVBiNThUUjdXaE9VYjRmTnc9PQ=="
  