apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9tZWxiaW5wcG1hdGhld3A6bWVsYmluMTIzNDU2QGdsYXNzaWNzLnBrMDNpaWoubW9uZ29kYi5uZXQvYWRtaW5fc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA=="
  ADMIN_ACCESS_SECRET_TOKEN: "MEpiA8u4AGLX/UE6t+FZ3Vq1ojsTSTPvn8OkI957fKcyANhbbF9o6GNaB0grT5gqf7kq9UPb58TR7WhOUb4fNw=="
  