apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
type: Opaque
data:
  ADMIN_ACCESS_SECRET_TOKEN: "TUVwaUE4dTRBR0xYL1VFNnQrRlozVnExb2pzVFNUUHZuOE9rSTk1N2ZLY3lBTmhiYkY5bzZHTmFCMGdyVDVncWY3a3E5VVBiNThUUjdXaE9VYjRmTnc9PQ=="
  USER_ACCESS_SECRET_TOKEN: "cWc2R0pWeWdGTVExZ2RqYWpZTFZzV3pQMzJyZlpGSkZubDNjRUlrNEhsTithTXpaU3NWTk40ZGpUSDRiejNuOWhERmNWNGRGSmp5d21jajhiVDdONEE9PQ=="