apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9tZWxiaW5wcG1hdGhld3A6bWVsYmluMTIzNDU2QGdsYXNzaWNzLnBrMDNpaWoubW9uZ29kYi5uZXQvYXV0aF9zZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw"
  ADMIN_ACCESS_SECRET_TOKEN: "MEpiA8u4AGLX/UE6t+FZ3Vq1ojsTSTPvn8OkI957fKcyANhbbF9o6GNaB0grT5gqf7kq9UPb58TR7WhOUb4fNw=="
  ADMIN_REFRESH_SECRET_TOKEN: "ReOEfONU4T8ZkJ40iCjfwwXklRTwKDqZNwWhi2oQmqUWwhoTGWrNKk4SGwpoPre5ykGBpVMSWx/VW9gr7i4Frg=="