apiVersion: v1
kind: Secret
metadata:
  name: user-secret
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9tZWxiaW5wcG1hdGhld3A6bWVsYmluMTIzNDU2QGdsYXNzaWNzLnBrMDNpaWoubW9uZ29kYi5uZXQvdXNlcl9zZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw"
  USER_ACCESS_SECRET_TOKEN: "qg6GJVygFMQ1gdjajYLVsWzP32rfZFJFnl3cEIk4HlN+aMzZSsVNN4djTH4bz3n9hDFcV4dFJjywmcj8bT7N4A=="