#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: appropriate/curl:latest
          command: ["sh", "-c", "until curl -f http://rabbitmq:15672; do echo waiting for RabbitMQ; sleep 5; done;"]
      containers:
        - name: user
          image: melbinmathewm/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret


---


#Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec: 
  type: ClusterIP
  selector: 
    app: user
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051